name: Deploy

on:
  push:
    branches:
      - main

env:
  ID: 脚手架
  TIPS_URL: https://wss.laihaojie.com/api/tools/releaseSuccess

permissions:
  contents: read

jobs:
  # packages =======================================================================================================================
  djie-cli:
    if: contains(github.event.head_commit.message, 'release')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16.x]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Publish
        run: npm publish --access public --registry https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=6144

      - name: Send success message
        if: success()
        run: curl -G ${{ env.TIPS_URL }} --data-urlencode "id=${{ env.ID }}"

      - name: Send failed message
        if: failure()
        run: curl -G ${{ env.TIPS_URL }} --data-urlencode "id=${{ env.ID }}"
